### ISSUE TITLE
Language issue: German Umlauts are not displayed properly in dropdown style and dashboard

### ISSUE THREAD

**Issue by Souiri-Ismail** [humdek-unibe-ch/sh-selfhelp_app#11]
![1 photo added](https://github.com/humdek-unibe-ch/sh-selfhelp_app/assets/151860538/ca703b4d-b159-431a-be1b-1e75e8c0ae8c)

**Comment by Kodzhabashev** [comment]
Fixed in SelfHelp v6.12.1
