### ISSUE TITLE
German Umlauts are not displyed properly in the drop-down menu

### ISSUE THREAD

**Issue by Souiri-Ismail** [humdek-unibe-ch/sh-selfhelp_app#16]
![1 photo added](https://github.com/humdek-unibe-ch/sh-selfhelp_app/assets/151860538/c38890bb-a753-446b-af4d-c4d7a7b12748)

**Comment by Kodzhabashev** [comment]
Fixed in SelfHelp v6.12.1, I will update the server later and it should be loaded normally on the mobile.
